### ISSUE TITLE
error muncul saat akses login

### ISSUE THREAD

**Issue by dhantos** [crocodic-studio/simple-stock-manager#1]
Sudah berhasil install, semua database telah di migrasi.

namun pada saat akses 127.0.0.1:8000/admin/login

muncul error berikut :
RuntimeException in Encrypter.php line 43: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

**Comment by fherryfherry** [comment]
Jalankan php artisan key:generate
Pada tanggal 21 Mar 2017 19.57, "dhani santoso" <notifications@github.com>
menulis:

**Comment by dhantos** [comment]
wah fast response ya mas. baru saja mau jawab pertanyaan sendiri. 

betul mas, berhasil setelah saya jalankan
**php artisan key:generate** dan **php artisan config:clear**

luar biasa mas.
